# Generated by Django 5.1.5 on 2025-02-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='users',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='users',
            name='telefone',
        ),
        migrations.AddField(
            model_name='professor',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='professor',
            name='endereco',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='professor',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
    ]
